### ISSUE TITLE
Show me an error when i am using dart_amqp with bloc 

### ISSUE THREAD

**Issue by lkrjangid1** [achilleasa/dart_amqp#70]
```
E/flutter (25971): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Unhandled error ConnectionFailedException: Could not connect to mustang.rmq.cloudamqp.com:5672 after 1 attempts. Giving up occurred in Instance of 'OneToOneMatchLiveScreenBloc'.
E/flutter (25971): 
E/flutter (25971): #0      BlocBase.onError.<anonymous closure> (package:bloc/src/bloc.dart:743:7)
E/flutter (25971): #1      BlocBase.onError (package:bloc/src/bloc.dart:744:6)
E/flutter (25971): #2      _rootRunBinary (dart:async/zone.dart:1452:47)
```

**Comment by mafejzuli** [comment]
I don't see any connection between the BLoC library and this one. Perhaps you didn't configure TLS properly as I'd guess cloudamqp.com is using that (this is a complete shot in the dark though as that error could be anything).

**Comment by achilleasa** [comment]
Closing this issue as it does not seem related to this library. Feel free to re-open it if you believe this is not the case.
